# Generated by Django 3.0 on 2019-12-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('run', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='Run')),
                ('nombre', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=30, verbose_name='Ciudad')),
                ('telefono', models.IntegerField(blank=True, max_length=10, verbose_name='Telefono')),
                ('correo', models.EmailField(blank=True, max_length=10, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, verbose_name='Nombre')),
                ('tipo_roedor', models.CharField(blank=True, max_length=20, verbose_name='Tipo')),
                ('ciudadM', models.CharField(blank=True, max_length=30, verbose_name='Cuidad')),
                ('infoM', models.TextField(blank=True, max_length=10, null=True, verbose_name='Información')),
            ],
        ),
    ]
