# Generated by Django 3.0 on 2019-12-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='telefono',
            field=models.IntegerField(blank=True, verbose_name='Telefono'),
        ),
    ]
