# Generated by Django 3.0 on 2019-12-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0002_auto_20191214_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Correo'),
        ),
    ]
