# Generated by Django 3.0 on 2019-12-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0004_auto_20191214_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='nombreM',
        ),
    ]
