# Generated by Django 3.0 on 2019-12-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0005_auto_20191214_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreM',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_roedor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Roedor'),
        ),
    ]
