# Generated by Django 3.0 on 2019-12-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0006_auto_20191214_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='telefono',
            field=models.IntegerField(blank=True, verbose_name='Telefono'),
        ),
    ]
