# Generated by Django 3.0 on 2019-12-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0007_auto_20191214_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha Adopción')),
                ('mascota_adop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Mascota')),
                ('run_adop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Adoptante')),
            ],
        ),
    ]
