# Generated by Django 3.0 on 2019-12-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0008_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='run_adop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Adoptante'),
        ),
    ]
